package picoplaca;

import javax.swing.JOptionPane;

/**
 *
 * @author Juan Aristizábal
 */
public class PicoPlacaGUI extends javax.swing.JFrame {

    /**
     * Creates new form PicoPlacaGUI
     */
    public PicoPlacaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timePickerLabel1 = new com.raven.swing.TimePickerLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        plateL = new javax.swing.JTextField();
        plateN = new javax.swing.JTextField();
        cbDay = new javax.swing.JComboBox<>();
        timePicker = new com.raven.swing.TimePicker();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        timePickerLabel1.setText("timePickerLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1030, 580));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Predictor");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pico y Placa");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 200));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Java based system that\nreturns whether or not\na car can be on the \nroad based in the last\ndigit of the license \nplate, the day of the \nweek, and the hour");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 250, 180));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 580));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("-");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Enter the Day of the Week:");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Enter the Time:");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Enter the License Plate Number:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        plateL.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        plateL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                plateLKeyPressed(evt);
            }
        });
        jPanel6.add(plateL, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 60, -1));

        plateN.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        plateN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                plateNKeyPressed(evt);
            }
        });
        jPanel6.add(plateN, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 60, -1));

        cbDay.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        cbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" }));
        jPanel6.add(cbDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        timePicker.setForeground(new java.awt.Color(0, 102, 102));
        timePicker.set24hourMode(true);
        jPanel6.add(timePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PREDICT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Pico y Placa Predictor");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jTabbedPane1.addTab("tab2", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 720, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //Check that the text fields are not empty
        if(plateL.getText().isBlank() || plateN.getText().isBlank()){
            JOptionPane.showMessageDialog(rootPane, "Enter the license plate correctly, make sure that the text fields are not empty!");
        }
        //Check that the first text field has exactly three letters
        else if(plateL.getText().length() != 3){
            JOptionPane.showMessageDialog(rootPane, "Enter exactly three letters in the first text field!");
            //Check that the second text field has at least three numbers
        }else if(plateN.getText().length() < 3){
            JOptionPane.showMessageDialog(rootPane, "Enter at least three numbers in the second text field");
        }else{
            //Join the two text fields together
            String plateValue = plateL.getText() + "-" + plateN.getText();
            //Create LicensePlate object
            LicensePlate licensePlate = new LicensePlate(plateValue);

            //Show results
            JOptionPane.showMessageDialog(rootPane, licensePlate.getResults(cbDay.getSelectedItem().toString(), timePicker.getSelectedTime()));

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void plateNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_plateNKeyPressed
        //Get the character from the event
        char c = evt.getKeyChar();

        //Check that the character is a digit or a control character
        if (Character.isDigit(c) || Character.isISOControl(c)) {
            plateN.setEditable(true);
        } else {
            plateN.setEditable(false);
        }

        //Check that the text in the text field is equal to four characters
        if (plateN.getText().length() == 4){

            //If the character is a control character, you can use it, if not, you can't insert more characters
            if(Character.isISOControl(c)){
                plateN.setEditable(true);
            }else{
                plateN.setEditable(false);
            }
        }
    }//GEN-LAST:event_plateNKeyPressed

    private void plateLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_plateLKeyPressed

        //Get the character from the event
        char c = evt.getKeyChar();

        //Check that the character is a letter or a control character
        if (Character.isLetter(c) || Character.isISOControl(c)) {
            plateL.setEditable(true);
        } else {
            plateL.setEditable(false);
        }

        //Check that the text in the text field is equal to three characters
        if (plateL.getText().length() == 3){

            //If the character is a control character, you can use it, if not, you can't insert more characters
            if(Character.isISOControl(c)){
                plateL.setEditable(true);
            }else{
                plateL.setEditable(false);
            }
        }

    }//GEN-LAST:event_plateLKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PicoPlacaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PicoPlacaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PicoPlacaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PicoPlacaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PicoPlacaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDay;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField plateL;
    private javax.swing.JTextField plateN;
    private com.raven.swing.TimePicker timePicker;
    private com.raven.swing.TimePickerLabel timePickerLabel1;
    // End of variables declaration//GEN-END:variables
}